spring:
  application:
    name: tpo-prog3

  data:
    neo4j:
      uri: bolt://localhost:7687
      database: neo4j   # esta l√≠nea apunta a la base activa
      authentication:
        username: neo4j
        password: neo4j123  # o la que pusiste al crear la instancia

server:
  port: 8080
